version: "3.9"

services:
  api:
    build:
      context: ./services/api
    ports:
      - "8000:8000"
    volumes:
      - ./services/api:/app
    # depends_on:
    #   - postgres
    env_file:
      - .env

  web:
    build:
      context: ./services/web
    ports:
      - "3000:3000"
    volumes:
      - ./services/web:/app
    depends_on:
      - api

  # postgres:
  #   image: postgres:16
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=parazit_db
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"